var irregulars = [
  ["abide","abode","abode","souffrir"],
  ["arise","arose","arisen","survenir"],
  ["awake",	"awoke",	"awoken",	"se réveiller"],
  ["be",	"was",	"been",	"être"],
  ["bear",	"bore",	"borne",	"porter"],
  ["beat",	"beat",	"beaten",	"battre"],
  ["become",	"became",	"become",	"devenir"],
  ["beget",	"begat",	"begotten",	"engendrer"],
  ["begin",	"began",	"begun",	"commencer"],
  ["bend",	"bent",	"bent",	"plier"],
  ["bereave",	"bereft",	"bereft",	"déposséder"],
  ["bet",	"bet",	"bet",	"parier"],
  ["bid",	"bid",	"bid",	"offrir"],
  ["bite",	"bit",	"bitten",	"mordre"],
  ["bleed",	"bled",	"bled",	"saigner"],
  ["blow", 	"blew",	"blown",	"souffler"],
  ["break",	"broke",	"broken",	"casser"],
  ["breed",	"bred",	"bred",	"élever"],
  ["bring",	"brought",	"brought",	"apporter"],
  ["broadcast",	"broadcast",	"broadcast",	"diffuser"],
  ["build",	"built",	"built",	"construire"],
  ["burn",	"burnt",	"burnt",	"brûler"],
  ["burst",	"burst",	"burst",	"éclater"],
  ["buy",	"bought",	"bought",	"acheter"],
  ["can",	"could",	"been able to",	"pouvoir"],
  // ["can",	"could",	"could",	"pouvoir"],
  ["cast",	"cast",	"cast",	"jeter"],
  ["catch",	"caught",	"caught",	"attraper"],
  ["chide",	"chid",	"chiden",	"gronder"],
  ["choose",	"chose",	"chosen",	"choisir"],
  ["cling",	"clung",	"clung",	"s’accrocher"],
  ["clothe",	"clad",	"clad",	"habiller"],
  ["come",	"came",	"come",	"venir"],
  ["cost",	"cost",	"cost",	"coûter"],
  ["creep",	"crept",	"crept",	"ramper"],
  ["cut",	"cut",	"cut",	"couper"],
  ["deal",	"dealt",	"dealt",	"distribuer"],
  ["dig",	"dug",	"dug",	"creuser"],
  ["dive",	"dove",	"dived",	"plonger"],
  ["do",	"did",	"done",	"faire"],
  ["draw",	"drew",	"drawn",	"dessiner"],
  ["dream",	"dreamt",	"dreamt",	"rêver"],
  ["drink",	"drank",	"drunk",	"boire"],
  ["drive",	"drove",	"driven",	"conduire"],
  ["dwell",	"dwelt",	"dwelt",	"habiter"],
  ["eat",	"ate",	"eaten",	"manger"],
  ["fall",	"fell",	"fallen",	"tomber"],
  ["feed",	"fed",	"fed",	"nourrir"],
  ["feel",	"felt",	"felt",	"se sentir"],
  ["fight",	"fought",	"fought",	"se battre"],
  ["find",	"found",	"found",	"trouver"],
  ["flee",	"fled",	"fled",	"s’enfuir"],
  ["fling",	"flung",	"flung",	"lancer"],
  ["fly",	"flew",	"flown",	"voler"],
  ["forbid",	"forbade",	"forbidden",	"interdire"],
  ["forecast",	"forecast",	"forecast",	"prévoir"],
  ["forget",	"forgot",	"forgotten",	"oublier"],
  ["forgive",	"forgave",	"forgiven",	"pardonner"],
  ["forsake",	"forsook",	"forsaken",	"abandonner"],
  ["forsee",	"foresaw",	"foresawn",	"prévoir"],
  ["freeze",	"froze",	"frozen",	"geler"],
  ["get",	"got",	"gotten",	"obtenir"],
  // ["get",	"got",	"got",	"obtenir"],
  ["give",	"gave",	"given",	"donner"],
  ["go",	"went",	"gone",	"aller"],
  ["grind",	"ground",	"ground",	"moudre"],
  ["grow",	"grew",	"grown",	"grandir"],
  ["hang",	"hung",	"hung",	"tenir"],
  ["have",	"had",	"had",	"avoir"],
  ["hear",	"heard",	"heard",	"entendre"],
  ["hide",	"hid",	"hidden",	"cacher"],
  ["hit",	"hit",	"hit",	"taper"],
  ["hold",	"held",	"held",	"tenir"],
  ["hurt",	"hurt",	"hurt",	"blesser"],
  ["keep",	"kept",	"kept",	"garder"],
  ["kneel",	"knelt",	"knelt",	"s’agenouiller"],
  ["know",	"knew",	"known",	"connaître"],
  ["lay",	"laid",	"laid",	"poser"],
  ["lead",	"led",	"led",	"mener"],
  ["lean",	"leant",	"leant",	"s’incliner"],
  ["leap",	"leapt",	"leapt",	"sauter"],
  ["learn",	"learnt",	"learnt",	"apprendre"],
  ["leave",	"left",	"left",	"laisser"],
  ["lend",	"lent",	"lent",	"prêter"],
  ["let",	"let",	"let",	"permettre"],
  ["lie",	"lay",	"lain",	"s’allonger"],
  ["light",	"lit",	"lit",	"allumer"],
  ["lose",	"lost",	"lost",	"perdre"],
  ["make",	"made",	"made",	"fabriquer"],
  ["mean",	"meant",	"meant",	"signifier"],
  ["meet",	"met",	"met",	"rencontrer"],
  ["mow",	"mowed",	"mown",	"tondre"],
  // ["mow",	"mowed",	"mowed",	"tondre"],
  ["offset",	"offset",	"offset",	"compenser"],
  ["overcome",	"overcame",	"overcome",	"surmonter"],
  ["partake",	"partook",	"partaken",	"prendre part à"],
  ["pay",	"paid",	"paid",	"payer"],
  ["plead",	"pled",	"pled",	"supplier"],
  ["preset",	"preset",	"preset",	"programmer"],
  ["prove",	"proved",	"proven",	"prouver"],
  ["put",	"put",	"put",	"mettre"],
  ["quit",	"quit",	"quit",	"quitter"],
  ["read",	"read",	"read",	"lire"],
  ["relay",	"relaid",	"relaid",	"relayer"],
  ["rend",	"rent",	"rent",	"déchirer"],
  ["rid",	"rid",	"rid",	"débarrasser"],
  ["ride",	"rode",	"ridden",	"monter"],
  ["ring",	"rang",	"rung",	"sonner"],
  ["rise",	"rose",	"risen",	"lever"],
  ["run",	"ran",	"run",	"courir"],
  ["saw",	"sawed",	"sawn",	"scier"],
  ["say",	"said",	"said",	"dire"],
  ["see",	"saw",	"seen",	"voir"],
  ["seek",	"sought",	"sought",	"chercher"],
  ["sell",	"sold",	"sold",	"vendre"],
  ["send",	"sent",	"sent",	"envoyer"],
  ["set",	"set",	"set",	"fixer"],
  ["shake",	"shook",	"shaken",	"secouer"],
  ["shed",	"shed",	"shed",	"répandre"],
  ["shine",	"shone",	"shone",	"briller"],
  ["shoe",	"shod",	"shod",	"chausser"],
  ["shoot",	"shot",	"shot",	"tirer"],
  ["show",	"showed",	"shown",	"montrer"],
  ["shut",	"shut",	"shut",	"fermer"],
  ["sing",	"sang",	"sung",	"chanter"],
  ["sink",	"sank",	"sunk",	"couler"],
  ["sit",	"sat",	"sat",	"s’asseoir"],
  ["slay",	"slew",	"slain",	"tuer"],
  ["sleep",	"slept",	"slept",	"dormir"],
  ["slide",	"slid",	"slid",	"glisser"],
  ["slink",	"slunk",	"slunk",	"s’en aller furtivement"],
  ["slit",	"slit",	"slit",	"fendre"],
  ["smell",	"smelt",	"smelt",	"sentir"],
  ["sow",	"sowed",	"sown",	"semer"],
  ["speak",	"spoke",	"spoken",	"parler"],
  ["speed",	"sped",	"sped",	"aller vite"],
  ["spell",	"spelt",	"spelt",	"épeler"],
  ["spend",	"spent",	"spent",	"dépenser"],
  ["spill",	"spilt",	"spilt",	"renverser"],
  ["spin",	"spun",	"spun",	"tourner"],
  ["spit",	"spat",	"spat",	"cracher"],
  // ["spit",	"spit",	"spit",	"cracher"],
  ["split",	"split",	"split",	"fendre"],
  ["spoil",	"spoilt",	"spoilt",	"gâcher"],
  ["spread",	"spread",	"spread",	"répandre"],
  ["spring",	"sprang",	"sprung",	"surgir"],
  ["stand",	"stood",	"stood",	"être debout"],
  ["steal",	"stole",	"stolen",	"voler"],
  ["stick",	"stuck",	"stuck",	"coller"],
  ["sting",	"stung",	"stung",	"piquer"],
  ["stink",	"stunk",	"stunk",	"puer"],
  // ["stink",	"stank",	"stunk",	"puer"],
  ["strew",	"strewed",	"strewn",	"éparpiller"],
  ["strike",	"struck",	"stricken",	"frapper"],
  ["strive",	"strove",	"striven",	"s’efforcer"],
  ["swear",	"swore",	"sworn",	"jurer"],
  ["sweat",	"sweat",	"sweat",	"suer"],
  ["sweep",	"swept",	"swept",	"balayer"],
  ["swell",	"swelled",	"swollen",	"gonfler"],
  ["swim",	"swam",	"swum",	"nager"],
  ["swing",	"swung",	"swung",	"se balancer"],
  ["take",	"took",	"taken",	"prendre"],
  ["teach",	"taught",	"taught",	"enseigner"],
  ["tear",	"tore",	"torn",	"déchirer"],
  ["tell",	"told",	"told",	"dire"],
  ["think",	"thought",	"thought",	"penser"],
  ["thrive",	"throve",	"thriven",	"prospérer"],
  ["throw",	"threw",	"thrown",	"jeter"],
  ["thrust",	"thrust",	"thrust",	"enfoncer"],
  ["tread",	"trod",	"trodden",	"piétiner quelque chose"],
  ["typeset",	"typeset",	"typeset",	"composer"],
  ["undergo",	"underwent",	"undergone",	"subir"],
  ["understand",	"understood",	"understood",	"comprendre"],
  ["wake",	"woke",	"woken",	"réveiller"],
  ["wear",	"wore",	"worn",	"porter"],
  ["weep",	"wept",	"wept",	"pleurer"],
  ["wet",	"wet",	"wet",	"mouiller"],
  ["win",	"won",	"won",	"gagner"],
  ["wind",	"wound",	"wound",	"remonter"],
  ["withdraw",	"withdrew",	"withdrawn",	"se retirer"],
  ["wring",	"wrung",	"wrung",	"tordre"],
  ["write", "wrote", "written", "écrire"]
]
